
CREATE TABLE `saidaitenspa` (
  `ISP_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `ISP_SAIDAMC` INT(11) DEFAULT NULL,
  
  `ISP_PRODUTO` INT(11) DEFAULT NULL,
  `ISP_QUANTIDADE` DECIMAL(10,2) DEFAULT NULL,
  `ISP_VL_VENDA` DECIMAL(10,2) DEFAULT NULL,
  
  
  
  `ISP_OBSERVACAO` TEXT,
  `ISP_DATA_CADASTRO` DATE DEFAULT NULL,
  `ISP_HORA_CADASTRO` TIME DEFAULT NULL,
  `ISP_SESSION_CAD` VARCHAR(50) DEFAULT NULL,
  `ISP_IP_CADASTRO` VARCHAR(50) DEFAULT NULL,
  `ISP_DATA_ALTTERACAO` DATE DEFAULT NULL,
  `ISP_HORA_ALTERACAO` TIME DEFAULT NULL,
  `ISP_SESSION_ALTER` VARCHAR(50) DEFAULT NULL,
  `ISP_IP_ALTERACAO` VARCHAR(50) DEFAULT NULL,
  `ISP_ID_ALTER` INT(11) DEFAULT NULL,
  `ISP_ID_CAD` INT(11) DEFAULT NULL,
  PRIMARY KEY (`ISP_ID`)
) ENGINE=INNODB AUTO_INCREMENT=10 DEFAULT CHARSET=latin1;
