
CREATE TABLE `saidamc` (
  `SMC_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `SMC_CODIGO` INT(11) DEFAULT NULL,
  
  `SMC_COD_FUN` INT(11) DEFAULT NULL,
  
  
  `SMC_OBSERVACAO` TEXT,
  `SMC_DATA_CADASTRO` DATE DEFAULT NULL,
  `SMC_HORA_CADASTRO` TIME DEFAULT NULL,
  `SMC_SESSION_CAD` VARCHAR(50) DEFAULT NULL,
  `SMC_IP_CADASTRO` VARCHAR(50) DEFAULT NULL,
  `SMC_DATA_ALTTERACAO` DATE DEFAULT NULL,
  `SMC_HORA_ALTERACAO` TIME DEFAULT NULL,
  `SMC_SESSION_ALTER` VARCHAR(50) DEFAULT NULL,
  `SMC_IP_ALTERACAO` VARCHAR(50) DEFAULT NULL,
  `SMC_ID_ALTER` INT(11) DEFAULT NULL,
  `SMC_ID_CAD` INT(11) DEFAULT NULL,
  PRIMARY KEY (`SMC_ID`)
) ENGINE=INNODB AUTO_INCREMENT=10 DEFAULT CHARSET=latin1;
