
CREATE TABLE `venitens` (
  `VNI_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `VNI_VEN_ID` INT(11) DEFAULT NULL,
  
  `VNI_ID_ISP` INT(11) DEFAULT NULL,
  `VNI_ID_PROD` INT(11) DEFAULT NULL,
  `VNI_QUANTIDADE` DECIMAL(10,2) NULL,

  
  `VNI_OBSERVACAO` TEXT,
  `VNI_DATA_CADASTRO` DATE DEFAULT NULL,
  `VNI_HORA_CADASTRO` TIME DEFAULT NULL,
  `VNI_SESSION_CAD` VARCHAR(50) DEFAULT NULL,
  `VNI_IP_CADASTRO` VARCHAR(50) DEFAULT NULL,
  `VNI_DATA_ALTTERACAO` DATE DEFAULT NULL,
  `VNI_HORA_ALTERACAO` TIME DEFAULT NULL,
  `VNI_SESSION_ALTER` VARCHAR(50) DEFAULT NULL,
  `VNI_IP_ALTERACAO` VARCHAR(50) DEFAULT NULL,
  `VNI_ID_ALTER` INT(11) DEFAULT NULL,
  `VNI_ID_CAD` INT(11) DEFAULT NULL,
  PRIMARY KEY (`VNI_ID`)
) ENGINE=INNODB AUTO_INCREMENT=10 DEFAULT CHARSET=latin1;
