
CREATE TABLE `vendas` (
  `VEN_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `VEN_CODIGO` INT(11) DEFAULT NULL,
  
  `VEN_ID_VEN_FUN` INT(11) DEFAULT NULL,
  `VEN_ID_CLI` INT(11) DEFAULT NULL,
  
  `VEN_TRANSP` VARCHAR(100) DEFAULT NULL,
  `VEN_F_PGMT` VARCHAR(100) DEFAULT NULL,
  `VEN_M_PGMT` VARCHAR(100) DEFAULT NULL,
  `VEN_VL_GASTO` DECIMAL(10,2) DEFAULT NULL,
  `VEN_VL_PARCELADO` DECIMAL(10,2) DEFAULT NULL,
  `VEN_VL_BRUTO` DECIMAL(10,2) DEFAULT NULL,
  
  
  `VEN_OBSERVACAO` TEXT,
  `VEN_DATA_CADASTRO` DATE DEFAULT NULL,
  `VEN_HORA_CADASTRO` TIME DEFAULT NULL,
  `VEN_SESSION_CAD` VARCHAR(50) DEFAULT NULL,
  `VEN_IP_CADASTRO` VARCHAR(50) DEFAULT NULL,
  `VEN_DATA_ALTTERACAO` DATE DEFAULT NULL,
  `VEN_HORA_ALTERACAO` TIME DEFAULT NULL,
  `VEN_SESSION_ALTER` VARCHAR(50) DEFAULT NULL,
  `VEN_IP_ALTERACAO` VARCHAR(50) DEFAULT NULL,
  `VEN_ID_ALTER` INT(11) DEFAULT NULL,
  `VEN_ID_CAD` INT(11) DEFAULT NULL,
  PRIMARY KEY (`VEN_ID`)
) ENGINE=INNODB AUTO_INCREMENT=10 DEFAULT CHARSET=latin1;
