
CREATE TABLE `pedido` (
  `PED_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `PED_CODIGO` INT(11) DEFAULT NULL,
  
  `PED_COD_FUN` INT(11) DEFAULT NULL,
  `PED_TIPO` VARCHAR(10) DEFAULT NULL,
  
  
  `PED_OBSERVACAO` TEXT,
  `PED_DATA_CADASTRO` DATE DEFAULT NULL,
  `PED_HORA_CADASTRO` TIME DEFAULT NULL,
  `PED_SESSION_CAD` VARCHAR(50) DEFAULT NULL,
  `PED_IP_CADASTRO` VARCHAR(50) DEFAULT NULL,
  `PED_DATA_ALTTERACAO` DATE DEFAULT NULL,
  `PED_HORA_ALTERACAO` TIME DEFAULT NULL,
  `PED_SESSION_ALTER` VARCHAR(50) DEFAULT NULL,
  `PED_IP_ALTERACAO` VARCHAR(50) DEFAULT NULL,
  `PED_ID_ALTER` INT(11) DEFAULT NULL,
  `PED_ID_CAD` INT(11) DEFAULT NULL,
  PRIMARY KEY (`PED_ID`)
) ENGINE=INNODB AUTO_INCREMENT=10 DEFAULT CHARSET=latin1;
