
CREATE TABLE `fornecedor` (
  `FOR_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `FOR_CODIGO` INT(11) DEFAULT NULL,
  
  `FOR_PESSOA` VARCHAR(10) DEFAULT NULL,
  `FOR_COD_PESSOA` VARCHAR(100) DEFAULT NULL,
  `FOR_VENDEDOR` VARCHAR(50) DEFAULT NULL,
  `FOR_VENCIMENTO` DATE DEFAULT NULL,
  `FOR_LIMITE` DECIMAL(10,2) DEFAULT NULL,
  `FOR_GERENTE` VARCHAR(50) DEFAULT NULL,
  
  
  `FOR_OBSERVACAO` TEXT,
  `FOR_DATA_CADASTRO` DATE DEFAULT NULL,
  `FOR_HORA_CADASTRO` TIME DEFAULT NULL,
  `FOR_SESSION_CAD` VARCHAR(50) DEFAULT NULL,
  `FOR_IP_CADASTRO` VARCHAR(50) DEFAULT NULL,
  `FOR_DATA_ALTTERACAO` DATE DEFAULT NULL,
  `FOR_HORA_ALTERACAO` TIME DEFAULT NULL,
  `FOR_SESSION_ALTER` VARCHAR(50) DEFAULT NULL,
  `FOR_IP_ALTERACAO` VARCHAR(50) DEFAULT NULL,
  `FOR_ID_ALTER` INT(11) DEFAULT NULL,
  `FOR_ID_CAD` INT(11) DEFAULT NULL,
  PRIMARY KEY (`FOR_ID`)
) ENGINE=INNODB AUTO_INCREMENT=10 DEFAULT CHARSET=latin1;
