
CREATE TABLE `itenspa` (
  `IPA_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `IPA_ENTRADAPA` INT(11) DEFAULT NULL,
  
  `IPA_PRODUTO` INT(11) DEFAULT NULL,
  `IPA_QUANTIDADE` VARCHAR(100) DEFAULT NULL,
  `IPA_PRECOUN` DECIMAL(10.2) DEFAULT NULL,
  `IPA_UN` VARCHAR(10) DEFAULT NULL,
  `IPA_CST` VARCHAR(200) DEFAULT NULL,
  `IPA_CFOP` VARCHAR(50) DEFAULT NULL,
  `IPA_NCMSH` VARCHAR(50) DEFAULT NULL,
  `IPA_SITUACAO` VARCHAR(100) DEFAULT NULL,
  
  
  `IPA_OBSERVACAO` TEXT,
  `IPA_DATA_CADASTRO` DATE DEFAULT NULL,
  `IPA_HORA_CADASTRO` TIME DEFAULT NULL,
  `IPA_SESSION_CAD` VARCHAR(50) DEFAULT NULL,
  `IPA_IP_CADASTRO` VARCHAR(50) DEFAULT NULL,
  `IPA_DATA_ALTTERACAO` DATE DEFAULT NULL,
  `IPA_HORA_ALTERACAO` TIME DEFAULT NULL,
  `IPA_SESSION_ALTER` VARCHAR(50) DEFAULT NULL,
  `IPA_IP_ALTERACAO` VARCHAR(50) DEFAULT NULL,
  `IPA_ID_ALTER` INT(11) DEFAULT NULL,
  `IPA_ID_CAD` INT(11) DEFAULT NULL,
  PRIMARY KEY (`IPA_ID`)
) ENGINE=INNODB AUTO_INCREMENT=10 DEFAULT CHARSET=latin1;
