
CREATE TABLE `entradapa` (
  `EPA_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `EPA_CODIGO` INT(11) DEFAULT NULL,
  
  `EPA_NOTA` VARCHAR(100) DEFAULT NULL,
  `EPA_COD_PESSOA` VARCHAR(100) DEFAULT NULL,
  `EPA_PEDIDO` VARCHAR(50) DEFAULT NULL,
  `EPA_RECEBIDO` INT(11) DEFAULT NULL,
  `EPA_CONT_FISCO` VARCHAR(200) DEFAULT NULL,
  `EPA_SERIE` VARCHAR(50) DEFAULT NULL,
  `EPA_PAGINA` VARCHAR(50) DEFAULT NULL,
  `EPA_NAT_OP` VARCHAR(100) DEFAULT NULL,
  `EPA_CH_NFE` VARCHAR(200) DEFAULT NULL,
  `EPA_DT_EMISSAO` DATE DEFAULT NULL,
  `EPA_DT_SAIDA` DATE DEFAULT NULL,
  `EPA_HR_SAIDA` TIME DEFAULT NULL,
  
  
  `EPA_OBSERVACAO` TEXT,
  `EPA_DATA_CADASTRO` DATE DEFAULT NULL,
  `EPA_HORA_CADASTRO` TIME DEFAULT NULL,
  `EPA_SESSION_CAD` VARCHAR(50) DEFAULT NULL,
  `EPA_IP_CADASTRO` VARCHAR(50) DEFAULT NULL,
  `EPA_DATA_ALTTERACAO` DATE DEFAULT NULL,
  `EPA_HORA_ALTERACAO` TIME DEFAULT NULL,
  `EPA_SESSION_ALTER` VARCHAR(50) DEFAULT NULL,
  `EPA_IP_ALTERACAO` VARCHAR(50) DEFAULT NULL,
  `EPA_ID_ALTER` INT(11) DEFAULT NULL,
  `EPA_ID_CAD` INT(11) DEFAULT NULL,
  PRIMARY KEY (`EPA_ID`)
) ENGINE=INNODB AUTO_INCREMENT=10 DEFAULT CHARSET=latin1;
