
CREATE TABLE `contap` (
  `CAP_ID` int(11) NOT NULL AUTO_INCREMENT,
  `CAP_CODIGO` int(11) DEFAULT NULL,
  
  `CAP_DESCRICAO` varchar(100) DEFAULT NULL,
  `CAP_CREDOR` varchar(100) DEFAULT NULL,
  `CAP_DOCUMENTO` varchar(50) DEFAULT NULL,
  `CAP_DT_VEN` date DEFAULT NULL,
  `CAP_VALOR` decimal(10,2) DEFAULT NULL,
  `CAP_N_P` int(11) DEFAULT NULL,
  `CAP_T_P` int(11) DEFAULT NULL,
  `CAP_VL_PAGO` decimal(10,2) DEFAULT NULL,
  `CAP_PAGO` varchar(5) DEFAULT NULL,
  `CAP_DT_PAGO` date DEFAULT NULL,
  
  `CAP_OBSERVACAO` text,
  `CAP_DATA_CADASTRO` date DEFAULT NULL,
  `CAP_HORA_CADASTRO` time DEFAULT NULL,
  `CAP_SESSION_CAD` varchar(50) DEFAULT NULL,
  `CAP_IP_CADASTRO` varchar(50) DEFAULT NULL,
  `CAP_DATA_ALTTERACAO` date DEFAULT NULL,
  `CAP_HORA_ALTERACAO` time DEFAULT NULL,
  `CAP_SESSION_ALTER` varchar(50) DEFAULT NULL,
  `CAP_IP_ALTERACAO` varchar(50) DEFAULT NULL,
  `CAP_ID_ALTER` int(11) DEFAULT NULL,
  `CAP_ID_CAD` int(11) DEFAULT NULL,
  PRIMARY KEY (`CAP_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=latin1;
