
CREATE TABLE `itensmc` (
  `IMC_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `IMC_ENTRADAPA` INT(11) DEFAULT NULL,
  
  `IMC_PRODUTO` INT(11) DEFAULT NULL,
  `IMC_QUANTIDADE` VARCHAR(100) DEFAULT NULL,
  `IMC_PRECOUN` DECIMAL(10.2) DEFAULT NULL,
  `IMC_UN` VARCHAR(10) DEFAULT NULL,
  `IMC_CST` VARCHAR(200) DEFAULT NULL,
  `IMC_CFOP` VARCHAR(50) DEFAULT NULL,
  `IMC_NCMSH` VARCHAR(50) DEFAULT NULL,
  `IMC_SITUACAO` VARCHAR(100) DEFAULT NULL,
  
  
  `IMC_OBSERVACAO` TEXT,
  `IMC_DATA_CADASTRO` DATE DEFAULT NULL,
  `IMC_HORA_CADASTRO` TIME DEFAULT NULL,
  `IMC_SESSION_CAD` VARCHAR(50) DEFAULT NULL,
  `IMC_IP_CADASTRO` VARCHAR(50) DEFAULT NULL,
  `IMC_DATA_ALTTERACAO` DATE DEFAULT NULL,
  `IMC_HORA_ALTERACAO` TIME DEFAULT NULL,
  `IMC_SESSION_ALTER` VARCHAR(50) DEFAULT NULL,
  `IMC_IP_ALTERACAO` VARCHAR(50) DEFAULT NULL,
  `IMC_ID_ALTER` INT(11) DEFAULT NULL,
  `IMC_ID_CAD` INT(11) DEFAULT NULL,
  PRIMARY KEY (`IMC_ID`)
) ENGINE=INNODB AUTO_INCREMENT=10 DEFAULT CHARSET=latin1;
